# [모의 캐글-의료] 흉부 CT 코로나 감염 여부 분류
- 이미지 binary 분류 과제
- 담당: 이녕민M

## Import Libraries

In [ ]:
!apt-get update && apt-get install -y python3-opencv

In [ ]:
!pip install sklearn

In [13]:
import os, torch, copy, cv2, sys, random, math
# from datetime import datetime, timezone, timedelta
from PIL import Image
import numpy as np
import pandas as pd
from tqdm import tqdm
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
import torchvision.transforms as transforms
import gc
from torchvision import models
from sklearn.metrics import confusion_matrix

## Set Arguments & hyperparameters

In [33]:
# 시드(seed) 설정

RANDOM_SEED = 2022

torch.manual_seed(RANDOM_SEED)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
np.random.seed(RANDOM_SEED)
random.seed(RANDOM_SEED)

In [34]:
# parameters

### 데이터 디렉토리 설정 ###
DATA_DIR= '/USER/Taeyun/'
NUM_CLS = 1

EPOCHS = 30
BATCH_SIZE = 32
LEARNING_RATE = 0.0005
EARLY_STOPPING_PATIENCE = 5
INPUT_SHAPE = 384

os.environ["CUDA_VISIBLE_DEVICES"]="0"
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

## Dataloader

#### Train & Validation Set loader

In [59]:
class CustomDataset(Dataset):
    def __init__(self, data_dir, mode, input_shape):
        self.data_dir = data_dir
        self.mode = mode
        self.input_shape = input_shape
        
        # Loading dataset
        self.db= self.data_loader()
        
        # Dataset split
        if self.mode == 'train':
            self.db = self.db.loc[:int(len(self.db)*0.7),:]
        elif self.mode == 'val':
            self.db = self.db.loc[int(len(self.db)*0.7):,:]
            self.db.reset_index(drop=True,inplace=True)
        else:
            print(f'!!! Invalid split {self.mode}... !!!')
            
        # Transform function
        self.transform = transforms.Compose([
                                             transforms.Resize(self.input_shape),
                                             transforms.ToTensor(),
                                             transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])])

    def data_loader(self):
        print('Loading ' + self.mode + ' dataset..')
        if not os.path.isdir(self.data_dir):
            print(f'!!! Cannot find {self.data_dir}... !!!')
            sys.exit()
        
        # (COVID : 1, No : 0)
        db = pd.read_csv(os.path.join(self.data_dir, 'train.csv'))
        new_db = pd.read_csv(os.path.join(self.data_dir,'new2.csv'))
        
        return pd.concat([new_db,db],axis=0,ignore_index=True)

    def __len__(self):
        return len(self.db)

    def __getitem__(self, index):
        data = copy.deepcopy(self.db.loc[index])
        flag = int(data['file_name'].split('.')[0])>=646
        # Loading image
        if not flag:
            cvimg = cv2.imread(os.path.join(self.data_dir,'train',data['file_name']), cv2.IMREAD_COLOR | cv2.IMREAD_IGNORE_ORIENTATION)
        else:
            cvimg = cv2.imread(os.path.join(self.data_dir,'newimg2',data['file_name']), cv2.IMREAD_COLOR | cv2.IMREAD_IGNORE_ORIENTATION)
        if not isinstance(cvimg, np.ndarray):
            raise IOError("Fail to read %s" % data['file_name'])

        # Preprocessing images
        trans_image = self.transform(Image.fromarray(cvimg))

        return trans_image, data['COVID']


## Model

In [60]:
import torch.nn.functional as F

class custom_CNN(nn.Module):
    def __init__(self, num_classes):
        super(custom_CNN, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=3, out_channels=8, kernel_size=5,padding=2)
        self.pool = nn.MaxPool2d(kernel_size=2,stride=2)
        self.conv2 = nn.Conv2d(in_channels=8, out_channels=25, kernel_size=5,padding=2)
        self.conv3 = nn.Conv2d(in_channels=25,out_channels=50,kernel_size=5)
        
        self.fc1 = nn.Linear(in_features=50*46*46, out_features=128)
        self.batchnorm = nn.BatchNorm1d(50*46*46)
        self.dropout = nn.Dropout(0.5)
        self.fc2 = nn.Linear(in_features=128, out_features=num_classes)        
    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x))) # (32, 3, 128, 128) -> (32, 8, 62, 62)
        x = self.pool(F.relu(self.conv2(x))) # (32, 8, 62, 62) -> (32, 25, 29, 29)
        x = self.pool(F.relu(self.conv3(x)))
        
        x = torch.flatten(x,1)
        x = self.dropout(F.relu(self.batchnorm(self.fc1(x))))
        x = self.fc2(x)
        
        output = torch.sigmoid(x)
        
        return output

## Utils
### EarlyStopper

In [61]:
class LossEarlyStopper():
    """Early stopper
    
    Attributes:
        patience (int): loss가 줄어들지 않아도 학습할 epoch 수
        patience_counter (int): loss 가 줄어들지 않을 때 마다 1씩 증가, 감소 시 0으로 리셋
        min_loss (float): 최소 loss
        stop (bool): True 일 때 학습 중단

    """

    def __init__(self, patience: int)-> None:
        self.patience = patience

        self.patience_counter = 0
        self.min_loss = np.Inf
        self.stop = False
        self.save_model = False

    def check_early_stopping(self, loss: float)-> None:
        """Early stopping 여부 판단"""  

        if self.min_loss == np.Inf:
            self.min_loss = loss
            return None

        elif loss > self.min_loss:
            self.patience_counter += 1
            msg = f"Early stopping counter {self.patience_counter}/{self.patience}"

            if self.patience_counter == self.patience:
                self.stop = True
                
                
        elif loss <= self.min_loss:
            self.patience_counter = 0
            self.save_model = True
            msg = f"Validation loss decreased {self.min_loss} -> {loss}"
            self.min_loss = loss
        
        print(msg)

### Trainer

In [62]:
class Trainer():
    """ epoch에 대한 학습 및 검증 절차 정의"""
    
    def __init__(self, loss_fn, model, device, metric_fn, optimizer=None, scheduler=None):
        """ 초기화
        """
        self.loss_fn = loss_fn
        self.model = model
        self.device = device
        self.optimizer = optimizer
        self.scheduler = scheduler
        self.metric_fn = metric_fn

    def train_epoch(self, dataloader, epoch_index):
        """ 한 epoch에서 수행되는 학습 절차"""
        self.model.train()
        self.model.cuda()
        train_total_loss = 0
        target_lst = []
        pred_lst = []
        prob_lst = []
        for batch_index, (img, label) in enumerate(dataloader):
            
            img = img.cuda()
            label = label.cuda().float()
            
            output,aux1,aux2 = self.model(img)
            output_loss = self.loss_fn(torch.sigmoid(output).view(-1),label)
            aux1_loss = self.loss_fn(torch.sigmoid(aux1).view(-1),label)
            aux2_loss = self.loss_fn(torch.sigmoid(aux2).view(-1),label)
            
            # 기존Resnet model에서의 output
            #pred = torch.sigmoid(self.model(img)).view(-1)
            
            loss = output_loss+0.3*(aux1_loss+aux1_loss)
            self.optimizer.zero_grad()
            loss.backward()
            self.optimizer.step()
            self.scheduler.step()
            
            train_total_loss += loss.item()
            #prob_lst.extend(pred[:, 1].cpu().tolist())
            target_lst.extend(label.cpu().tolist())
            pred_lst.extend((torch.sigmoid(output).view(-1)>0.5).int().cpu().tolist())
            #del pred
            
        self.train_mean_loss = train_total_loss / batch_index
        self.train_score, f1 = self.metric_fn(y_pred=pred_lst, y_answer=target_lst)
        msg = f'Epoch {epoch_index}, Train loss: {self.train_mean_loss}, Acc: {self.train_score}, F1-Macro: {f1}'
        del img
        del label
        gc.collect()
        torch.cuda.empty_cache()
        print(msg)

    def validate_epoch(self, dataloader, epoch_index):
        """ 한 epoch에서 수행되는 검증 절차
        """
        self.model.eval()
        self.model.cuda()
        val_total_loss = 0
        target_lst = []
        pred_lst = []
        prob_lst = []

        for batch_index, (img, label) in enumerate(dataloader):
            img = img.cuda()
            label = label.float().cuda()          
            
            pred = torch.sigmoid(self.model(img)).view(-1)
            
            loss = self.loss_fn(pred,label)
            val_total_loss += loss.item()
            #prob_lst.extend(pred[:, 1].cpu().tolist())
            target_lst.extend(label.cpu().tolist())
            pred_lst.extend((pred>0.5).int().cpu().tolist())
        self.val_mean_loss = val_total_loss / batch_index
        self.validation_score, f1 = self.metric_fn(y_pred=pred_lst, y_answer=target_lst)
        msg = f'Epoch {epoch_index}, Val loss: {self.val_mean_loss}, Acc: {self.validation_score}, F1-Macro: {f1}'
        print(confusion_matrix(target_lst,pred_lst))
        print(msg)
        del img
        del label
        gc.collect()
        torch.cuda.empty_cache()
        return self.validation_score

### Metrics

In [63]:
from sklearn.metrics import accuracy_score, f1_score

def get_metric_fn(y_pred, y_answer):
    """ 성능을 반환하는 함수"""
    
    assert len(y_pred) == len(y_answer), 'The size of prediction and answer are not same.'
    accuracy = accuracy_score(y_answer, y_pred)
    f1 = f1_score(y_answer, y_pred, average='macro')
    return accuracy, f1

## Train
### 학습을 위한 객체 선언

#### Load Dataset & Dataloader

In [64]:
# Load dataset & dataloader
train_dataset = CustomDataset(data_dir=DATA_DIR, mode='train', input_shape=INPUT_SHAPE)
validation_dataset = CustomDataset(data_dir=DATA_DIR, mode='val', input_shape=INPUT_SHAPE)
train_dataloader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
validation_dataloader = DataLoader(validation_dataset, batch_size=BATCH_SIZE, shuffle=True)
print('Train set samples:',len(train_dataset),  'Val set samples:', len(validation_dataset))

Loading train dataset..
Loading val dataset..
Train set samples: 10502 Val set samples: 4501


In [65]:
model = models.GoogLeNet(num_classes=1,init_weights=False)
model

GoogLeNet(
  (conv1): BasicConv2d(
    (conv): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (bn): BatchNorm2d(64, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
  )
  (maxpool1): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=True)
  (conv2): BasicConv2d(
    (conv): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (bn): BatchNorm2d(64, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
  )
  (conv3): BasicConv2d(
    (conv): Conv2d(64, 192, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn): BatchNorm2d(192, eps=0.001, momentum=0.1, affine=True, track_running_stats=True)
  )
  (maxpool2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=True)
  (inception3a): Inception(
    (branch1): BasicConv2d(
      (conv): Conv2d(192, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn): BatchNorm2d(64, eps=0.001, momentum=0.1, affine=True, track

#### Load model and other utils

In [66]:
# Load Model
#model = custom_CNN(NUM_CLS).to(DEVICE)

# # Save Initial Model
# torch.save(model.state_dict(), 'initial.pt')

# Set optimizer, scheduler, loss function, metric function
optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)
scheduler =  optim.lr_scheduler.OneCycleLR(optimizer=optimizer, pct_start=0.1, div_factor=1e5, max_lr=0.0001, epochs=EPOCHS, steps_per_epoch=len(train_dataloader))
loss_fn = nn.BCELoss()
metric_fn = get_metric_fn


# Set trainer
trainer = Trainer(loss_fn, model, DEVICE, metric_fn, optimizer, scheduler)

# Set earlystopper
early_stopper = LossEarlyStopper(patience=EARLY_STOPPING_PATIENCE)

### epoch 단위 학습 진행

In [67]:
val_acc=0
acc_cnt=0
for epoch_index in tqdm(range(EPOCHS)):
    trainer.train_epoch(train_dataloader, epoch_index)
    value = trainer.validate_epoch(validation_dataloader, epoch_index)
    
    
    #가장 높은 ACC모델 저장
    if value>=val_acc:
        if value>0.9999:
            acc_cnt+=1
            if acc_cnt==3:
                break
        else:
            acc_cnt=0
        val_acc = value
        check_point = {
            "model" : model.state_dict(),
            "optimizer" : optimizer.state_dict(),
            "scheduler" : scheduler.state_dict()            
        }
        torch.save(check_point,'best_acc.pt')
    # early_stopping check
    early_stopper.check_early_stopping(loss=trainer.val_mean_loss)
    if early_stopper.stop:
        print('Early stopped')
        break

    if early_stopper.save_model:
        check_point = {
            'model': model.state_dict(),
            'optimizer': optimizer.state_dict(),
            'scheduler': scheduler.state_dict()
        }
        torch.save(check_point, 'best_loss.pt')


  0% 0/30 [00:00<?, ?it/s]

Epoch 0, Train loss: 0.8879306902427498, Acc: 0.6830127594743858, F1-Macro: 0.662060116721304
[[2060  210]
 [  27 2204]]
Epoch 0, Val loss: 0.139556853659451, Acc: 0.9473450344367919, F1-Macro: 0.9472910844877266


  3% 1/30 [29:38<14:19:49, 1778.94s/it]

Epoch 1, Train loss: 0.14059331824878094, Acc: 0.987335745572272, F1-Macro: 0.9873357362714585


  7% 2/30 [58:22<13:42:27, 1762.42s/it]

[[1754  516]
 [   1 2230]]
Epoch 1, Val loss: 0.2537235228078706, Acc: 0.8851366363030437, F1-Macro: 0.8838374784880014
Early stopping counter 1/5
Epoch 2, Train loss: 0.06281069222917189, Acc: 0.9852409064940011, F1-Macro: 0.9852408474798748


 10% 3/30 [1:26:29<13:02:49, 1739.62s/it]

[[2268    2]
 [ 675 1556]]
Epoch 2, Val loss: 0.4633758661470243, Acc: 0.8495889802266163, F1-Macro: 0.8457286246186917
Early stopping counter 2/5
Epoch 3, Train loss: 0.018708209617016552, Acc: 0.9977147210055227, F1-Macro: 0.9977147209226418
[[2269    1]
 [   7 2224]]
Epoch 3, Val loss: 0.01734928088907119, Acc: 0.9982226171961787, F1-Macro: 0.9982224395191069
Validation loss decreased 0.139556853659451 -> 0.01734928088907119


 13% 4/30 [2:04:13<13:42:05, 1897.12s/it]

Epoch 4, Train loss: 0.013103529211526264, Acc: 0.9986669205865549, F1-Macro: 0.9986669205382077
[[1236 1034]
 [ 592 1639]]
Epoch 4, Val loss: 2.4547091752290724, Acc: 0.638746945123306, F1-Macro: 0.6358275074699231
Early stopping counter 1/5


 17% 5/30 [2:38:35<13:31:00, 1946.44s/it]

Epoch 5, Train loss: 0.14369299833339116, Acc: 0.9653399352504285, F1-Macro: 0.9653391495894297
[[1916  354]
 [   6 2225]]
Epoch 5, Val loss: 0.21503939691797963, Acc: 0.9200177738280382, F1-Macro: 0.9196390312802527
Early stopping counter 2/5


 20% 6/30 [3:09:51<12:50:06, 1925.28s/it]

Epoch 6, Train loss: 0.013500923301230282, Acc: 0.9975242810893163, F1-Macro: 0.9975242809995285
[[2270    0]
 [  24 2207]]
Epoch 6, Val loss: 0.04166291930138998, Acc: 0.9946678515885359, F1-Macro: 0.9946668067470839
Early stopping counter 3/5


 23% 7/30 [3:32:06<11:10:08, 1748.21s/it]

Epoch 7, Train loss: 0.0058007956940855365, Acc: 0.9995239002094839, F1-Macro: 0.9995239001706333
[[2270    0]
 [   8 2223]]
Epoch 7, Val loss: 0.017145486536589618, Acc: 0.9982226171961787, F1-Macro: 0.9982224233728618
Validation loss decreased 0.01734928088907119 -> 0.017145486536589618


 27% 8/30 [3:54:42<9:57:53, 1630.60s/it] 

Epoch 8, Train loss: 0.009941451990460159, Acc: 0.9987621405446582, F1-Macro: 0.9987621402640712
[[2270    0]
 [1839  392]]
Epoch 8, Val loss: 3.0877104657036916, Acc: 0.5914241279715619, F1-Macro: 0.505302347575026
Early stopping counter 1/5


 30% 9/30 [4:20:40<9:23:07, 1608.94s/it]

Epoch 9, Train loss: 0.042976463001672884, Acc: 0.9884783850695106, F1-Macro: 0.9884783799507407
[[2270    0]
 [   7 2224]]
Epoch 9, Val loss: 0.018458485963544394, Acc: 0.9984447900466563, F1-Macro: 0.9984446275920507
Early stopping counter 2/5


 33% 10/30 [4:47:04<8:53:46, 1601.31s/it]

Epoch 10, Train loss: 0.005043582264855703, Acc: 0.9990478004189678, F1-Macro: 0.9990478002808327
[[2224   46]
 [   6 2225]]
Epoch 10, Val loss: 0.04320670927741698, Acc: 0.988447011775161, F1-Macro: 0.9884470112048966
Early stopping counter 3/5


 37% 11/30 [5:14:12<8:29:35, 1609.23s/it]

Epoch 11, Train loss: 0.002945645481393113, Acc: 0.9995239002094839, F1-Macro: 0.9995239002051672
[[2270    0]
 [   7 2224]]
Epoch 11, Val loss: 0.021162983045074465, Acc: 0.9984447900466563, F1-Macro: 0.9984446275920507
Early stopping counter 4/5


 40% 12/30 [5:38:20<7:48:16, 1560.91s/it]

Epoch 12, Train loss: 0.0072652972813202505, Acc: 0.9994286802513807, F1-Macro: 0.9994286801684996


 40% 12/30 [5:57:48<8:56:42, 1789.01s/it]

[[2270    0]
 [1224 1007]]
Epoch 12, Val loss: 1.4340500124863216, Acc: 0.7280604310153299, F1-Macro: 0.704818174531361
Early stopping counter 5/5
Early stopped


## Inference
### 모델 로드

In [68]:
LOSS_MODEL_PATH = 'best_loss.pt'
ACC_MODEL_PATH = 'best_acc.pt'

### Load dataset

In [69]:
class TestDataset(Dataset):
    def __init__(self, data_dir, input_shape):
        self.data_dir = data_dir
        self.input_shape = input_shape
        
        # Loading dataset
        self.db = self.data_loader()
        
        # Transform function
        self.transform = transforms.Compose([transforms.Resize(self.input_shape),
                                             transforms.ToTensor(),
                                             transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])])

    def data_loader(self):
        print('Loading test dataset..')
        if not os.path.isdir(self.data_dir):
            print(f'!!! Cannot find {self.data_dir}... !!!')
            sys.exit()
        
        db = pd.read_csv(os.path.join(self.data_dir, 'sample_submission.csv'))
        return db
    
    def __len__(self):
        return len(self.db)
    
    def __getitem__(self, index):
        data = copy.deepcopy(self.db.loc[index])
        
        # Loading image
        cvimg = cv2.imread(os.path.join(self.data_dir,'test',data['file_name']), cv2.IMREAD_COLOR | cv2.IMREAD_IGNORE_ORIENTATION)
        if not isinstance(cvimg, np.ndarray):
            raise IOError("Fail to read %s" % data['file_name'])

        # Preprocessing images
        trans_image = self.transform(Image.fromarray(cvimg))

        return trans_image, data['file_name']

In [70]:
# Load dataset & dataloader
test_dataset = TestDataset(data_dir=DATA_DIR, input_shape=INPUT_SHAPE)
test_dataloader = DataLoader(dataset=test_dataset, batch_size=BATCH_SIZE, shuffle=False)

Loading test dataset..


### 추론 진행& 결과저장

In [71]:
model.load_state_dict(torch.load(LOSS_MODEL_PATH)['model'])

# Prediction
file_lst = []
pred_lst = []
prob_lst = []
model.eval()
with torch.no_grad():
    model.cuda()
    for batch_index, (img, file_num) in tqdm(enumerate(test_dataloader)):
        img = img.to(DEVICE)
        pred = torch.sigmoid(model(img)).view(-1)
        file_lst.extend(list(file_num))
        pred_lst.extend((pred>0.5).int().tolist())
        #prob_lst.extend(pred[:, 1].tolist())

4it [00:06,  1.74s/it]


In [72]:
df = pd.DataFrame({'file_name':file_lst, 'COVID':pred_lst})
# df.sort_values(by=['file_name'], inplace=True)
df.to_csv('loss_prediction.csv', index=False)

In [73]:
model.load_state_dict(torch.load(ACC_MODEL_PATH)['model'])

# Prediction
file_lst = []
pred_lst = []
prob_lst = []
model.eval()
with torch.no_grad():
    model.cuda()
    for batch_index, (img, file_num) in tqdm(enumerate(test_dataloader)):
        img = img.to(DEVICE)
        pred = torch.sigmoid(model(img)).view(-1)
        file_lst.extend(list(file_num))
        pred_lst.extend((pred>0.5).int().tolist())
        #prob_lst.extend(pred[:, 1].tolist())

4it [00:06,  1.53s/it]


In [74]:
df = pd.DataFrame({'file_name':file_lst, 'COVID':pred_lst})
# df.sort_values(by=['file_name'], inplace=True)
df.to_csv('acc_prediction.csv', index=False)